"""empty message

Revision ID: 19f4a2511e1
Revises: 1f87d330b27
Create Date: 2018-11-12 04:57:11.628172

"""

# revision identifiers, used by Alembic.
revision = '19f4a2511e1'
down_revision = '1f87d330b27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracefiles', sa.Column('status', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracefiles', 'status')
    ### end Alembic commands ###
