"""empty message

Revision ID: 1f87d330b27
Revises: 14ccf617613
Create Date: 2018-11-06 04:17:03.696055

"""

# revision identifiers, used by Alembic.
revision = '1f87d330b27'
down_revision = '14ccf617613'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('command', sa.String(length=100), nullable=True),
    sa.Column('process_id', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('templates')
    ### end Alembic commands ###
